### ISSUE TITLE
Suggestion to avoid lawsuits.

### ISSUE THREAD

**Issue by twojapiez** [melodyjkah/temprosnehook#1]
Hello this is me twojapies aka twojstaryhook.cc developer. Cleary i do not work for valve so as their not lawyer i advise you to remove all repositories mentioning or that are connected to "rosnehook". The files you share are NOT made by you and are NOT legal in the artarctica where you live. For more info on the topic please visit http://192.168.0.1:80/ and please review the following file: C:\Users\Twojapies\Documents\lawsuit.pdf 
I hope this message finds you well.
- TwodżaPiS

**Comment by melodyjkah** [comment]
😲☹☹☹☹

**Comment by melodyjkah** [comment]
closed because i have valvebypass.exe :)

**Comment by twojapiez** [comment]
so hacker wtf
