### ISSUE TITLE
thisshitissobroken

### ISSUE THREAD

**Issue by vKarkalicious** [melodyjkah/temprosnehook#2]
melody how u mess up worse than the 9 yr old rosne wannabe??
just post ipc and rosnebot KURWAAA
![image](https://github.com/melodyjkah/temprosnehook/assets/134182010/f279390e-375d-45d4-9e1e-ad2567f8ee72)

**Comment by melodyjkah** [comment]
issue closed because u are retarded, and its temprosnehook not rosnebot-setup.
